src/Entity/Campaign.php
<?php

namespace App\Entity;

use App\Repository\CampaignRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: CampaignRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Campaign implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'campaign', targetEntity: Child::class, orphanRemoval: true)]
    private Collection $children;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];
    #[ORM\Column]
    private ?int $numberOfMale = null;

    #[ORM\Column]
    private ?int $numberOfFemale = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTimeImmutable());
        }
    }

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Child>
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    /**
     * @return Collection<int, Child>
     */
    public function getShuffledChildren(): array
    {
        $entries = $this->children->toArray();
        shuffle($entries);
        $entriesGifted = array_filter($entries, function (Child $child) {
            return $child->getDonor() !== null;
        });
        $entriesUngifted = array_filter($entries, function (Child $child) {
            return $child->getDonor() === null;
        });
        return array_merge($entriesUngifted, $entriesGifted);
    }

    public function addChild(Child $child): static
    {
        if (!$this->children->contains($child)) {
            $this->children->add($child);
            $child->setCampaign($this);
        }

        return $this;
    }

    public function removeChild(Child $child): static
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getCampaign() === $this) {
                $child->setCampaign(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getNumberOfMale(): ?int
    {
        return $this->numberOfMale;
    }

    public function setNumberOfMale(int $numberOfMale): static
    {
        $this->numberOfMale = $numberOfMale;

        return $this;
    }

    public function getNumberOfFemale(): ?int
    {
        return $this->numberOfFemale;
    }

    public function setNumberOfFemale(int $numberOfFemale): static
    {
        $this->numberOfFemale = $numberOfFemale;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getRoles(): array
    {

        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
        // TODO: Implement getRoles() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        // TODO: Implement getUserIdentifier() method.
        return $this->getId();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/CampaignController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Entity\Child;
use App\Entity\Donor;
use App\Repository\CampaignRepository;
use App\Repository\ChildRepository;
use App\Repository\ChildTemplateRepository;
use App\Repository\DonorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\WrappedTemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\AsciiSlugger;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mime\Address;
use Psr\Log\LoggerInterface;
use Symfony\Component\Mime\Crypto\DkimSigner;
use Twig\Environment;
use Symfony\Bundle\SecurityBundle\Security;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class CampaignController extends AbstractController
{

    // constructor
    private LoggerInterface $logger;
    private KernelInterface $appKernel;
    private Environment $twig;
    private TranslatorInterface $translator;
    private MailerInterface $mailer;
    private CampaignRepository $campaignRepository;

    public function __construct(
        LoggerInterface     $logger,
        KernelInterface     $appKernel,
        Environment         $twig,
        TranslatorInterface $translator,
        MailerInterface     $mailer,
        CampaignRepository  $campaignRepository,
    )
    {
        $this->logger = $logger;
        $this->appKernel = $appKernel;
        $this->twig = $twig;
        $this->translator = $translator;
        $this->mailer = $mailer;
        $this->campaignRepository = $campaignRepository;
    }

    #[Route('/campaign/view/{slug}', name: 'app_show_campaign')]
    public function index(
        CampaignRepository $campaignRepository,
        Campaign           $campaign,
    ): Response
    {
        return $this->render('campaign/index.html.twig', [
            'campaign' => $campaign,
            'controller_name' => 'CampaignController',
        ]);
    }

    #[Route('/campaign/thank-you/{slug}', name: 'app_thank_you_donor')]
    public function thankYou(CampaignRepository $campaignRepository, Campaign $campaign): Response
    {
        return $this->render('campaign/appThankYouDonor.html.twig', [
            'campaign' => $campaign,
            'controller_name' => 'CampaignController',
        ]);
    }


    #[Route('/campaign/resend-confirmation-email/{id}', name: 'app_resend_confirmation_email')]
    public function resendConfirmationEmail(
        CampaignRepository $campaignRepository,
        Donor              $donor,
        Security           $security,
    ): Response
    {
        // check if user is campaign owner
        if ($donor->getChild()->getCampaign() === $security->getUser()) {
            $this->sendConfirmationEmail($donor);
        }
        return $this->redirectToRoute('app_show_campaign', [
            'slug' => $donor->getChild()->getCampaign()->getSlug()
        ]);
    }


    #[Route('/campaign/export/{slug}', name: 'app_export_campaign')]
    public function export(
        CampaignRepository $campaignRepository,
        DonorRepository    $donorRepository,
        Security           $security,
        Campaign           $campaign,
    )
    {
        // check if user is campaign owner
        if ($campaign === $security->getUser()) {
            // export donors to excel
            $spreadsheet = new Spreadsheet();
            $sheet = $spreadsheet->getActiveSheet();
            $sheet->setCellValue('A1', 'Firstname');
            $sheet->setCellValue('B1', 'Surname');
            $sheet->setCellValue('C1', 'Phone');
            $sheet->setCellValue('D1', 'Email');
            $sheet->setCellValue('E1', 'Child Name');
            $sheet->setCellValue('F1', 'Child Identifier');
            $sheet->setCellValue('G1', 'Child Age');
            $sheet->setCellValue('H1', 'Campaign');
            $sheet->setCellValue('I1', 'Created At');

            // loop donors
            $donors = $donorRepository->getByCampaign($campaign);
            $index = 2;
            /** @var Donor $donor */
            foreach ($donors as $donor) {
                $sheet->setCellValue('A' . $index, $donor->getFirstname());
                $sheet->setCellValue('B' . $index, $donor->getSurname());
                $sheet->setCellValue('C' . $index, $donor->getPhone());
                $sheet->setCellValue('D' . $index, $donor->getEmail());
                $sheet->setCellValue('E' . $index, $donor->getChild()->getFirstname());
                $sheet->setCellValue('F' . $index, $donor->getChild()->getIdentifier());
                $sheet->setCellValue('G' . $index, $donor->getChild()->getAge());
                $sheet->setCellValue('H' . $index, $donor->getChild()->getCampaign()->getTitle());
                $sheet->setCellValue('I' . $index, $donor->getCreatedAt());
                $index++;
            }

            // export spreadsheet
            $writer = new Xlsx($spreadsheet);
            $fileName = 'export-' . $campaign->getSlug() . '.xlsx';
            $writer->save($fileName);
            // download excel with symfony response
            return new BinaryFileResponse($fileName);

        }
    }

    #[Route('/campaign/become-a-donor/{id}', name: 'app_become_a_donor_campaign')]
    public function becomeADonor(
        CampaignRepository     $campaignRepository,
        TranslatorInterface    $translator,
        EntityManagerInterface $entityManager,
        Request                $request,
        Child                  $child,
    ): Response
    {
        $donor = new Donor();

        $form = $this->createFormBuilder($donor)
            ->add('firstname', TextType::class, [
                'label' => $translator->trans('firstname') . ' *',
                'required' => true,
            ])
            ->add('surname', TextType::class, [
                'label' => $translator->trans('surname') . ' *',
                'required' => true,
            ])
            ->add('phone', TextType::class, [
                'label' => $translator->trans('phone') . ' *',
                'required' => true,
            ])
            ->add('email', EmailType::class, [
                'label' => $translator->trans('email') . ' *',
                'required' => true,
            ])
            ->add('save', SubmitType::class, ['label' => $translator->trans('become.a.donor')])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $donor->setChild($child);

            $entityManager->persist($donor);
            $entityManager->flush();

            $this->sendConfirmationEmail($donor);

            return $this->redirectToRoute('app_thank_you_donor', [
                'slug' => $child->getCampaign()->getSlug()
            ]);
        }

        return $this->render('campaign/becomeAChild.html.twig', [
            'child' => $child,
            'form' => $form,
            'controller_name' => 'CampaignController',
        ]);
    }

    /*
        #[Route('/campaign/generate-children/{slug}', name: 'app_show_campaign')]
        public function generateChildren(
            ChildTemplateRepository $childTemplateRepository,
            ChildRepository         $childRepository,
            CampaignRepository      $campaignRepository,
            EntityManagerInterface  $entityManager,
            string                  $slug
        ): Response
        {
            $campaign = $campaignRepository
                ->findOneBy(['slug' => $slug]);

            foreach (Child::$GENDER as $key => $gender) {
                while ($campaign->getNumberOfFemale() > $childRepository->getNumberOfChildrenByGenderAndCampaign($key, $campaign)) {
                    $child = new Child();
                    $template = $childTemplateRepository->findRandomTemplateByGender($key);
                    $child->setFirstName($template->getFirstName());
                    $child->setGender($template->getGender());
                    $child->setCampaign($campaign);
                    $entityManager->persist($child);
                    $entityManager->flush();
                }
            }

            return $this->render('campaign/index.html.twig', [
                'campaign' => $campaign,
                'controller_name' => 'CampaignController',
            ]);
        }

        #[Route('/campaign/create', name: 'app_create_campaign')]
        public function create(ValidatorInterface $validator, EntityManagerInterface $entityManager, CampaignRepository $campaignRepository): Response
        {
            $campaign = new Campaign();
            $slugger = new AsciiSlugger();
            $campaign->setSlug($slugger->slug(uniqid())->lower());

            $errors = $validator->validate($campaign);
            if (count($errors) > 0) {
                return new Response((string)$errors, 400);
            }
            $entityManager->persist($campaign);
            $entityManager->flush();
            // redirect to index controiller
            return $this->redirectToRoute('app_show_campaign', [
                'slug' => $campaign->getSlug()
            ]);
        }*/
    private function sendConfirmationEmail(Donor $donor): void
    {

templates/campaign/appThankYouDonor.html.twig
{% extends 'base.html.twig' %}

{% block title %}Svitlo - {{ campaign.title }}{% endblock %}

{% block body %}
    <h1>{{ 'thank.you'|trans }}</h1>
    <p>{{ 'you.will.get.an.email.with.all.informations'|trans }}</p>
    <a class="btn btn-default"
       href="{{ path('app_show_campaign', {slug: campaign.slug}) }}">{{ 'back.to.the.campaign'|trans }}</a>
{% endblock %}

templates/campaign/becomeAChild.html.twig
{% extends 'base.html.twig' %}

{% block title %}Svitlo {{ child.campaign.title }}{% endblock %}

{% block body %}

    <a class="btn btn-secondary"
       href="{{ path('app_show_campaign', {slug: child.campaign.slug}) }}">{{ 'back.to.the.campaign'|trans }}</a>
    <h1>{{ child.firstName }}</h1>
    <p>{{ 'age'|trans }}: {{ child.age }}
        <br>{{ 'gender'|trans }}: {% if child.gender|gender == 'male' %}{{ 'male'|trans }}{% elseif child.gender|gender == 'female' %}{{ 'female'|trans }}{% endif %}</p>
    {{ form(form) }}
{% endblock %}

templates/campaign/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Svitlo - {{ campaign.title }}{% endblock %}

{% block body %}
    <h1>{{ campaign.title }}</h1>
    {% if is_granted('IS_AUTHENTICATED_FULLY') and app.user == campaign %}
        <a href="{{ path('app_export_campaign', {'slug': campaign.slug}) }}" class="btn btn-secondary">{{ 'export'|trans }}</a>
    {% endif %}
    {% if campaign.description %}
        <div class="row">
            <div class="col">
                {{ campaign.description|raw }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col">
            <h2>{{ 'choose.a.child'|trans }}</h2>
        </div>
    </div>
    <div class="row row-cols-3 g-3">
        {% for child in campaign.shuffledChildren %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ child.firstName }}</h5>
                        <p class="card-text">{% if child.age %}{{ 'age'|trans }}: {{ child.age }}{% endif %}
                            {% if child.gender %}<br>{{ 'gender'|trans }}: {{ child.gender|gender|trans }}{% endif %}
                            {% if child.identifier %}<br>{{ 'identifier'|trans }}: {{ child.identifier }}{% endif %}</p>

                        {% if is_granted('IS_AUTHENTICATED_FULLY') and app.user == campaign and child.donor %}
                            <a href="{{ path('app_resend_confirmation_email', {id: child.donor.id}) }}"
                               class="btn btn-primary">{{ 'resend.confirmation.email'|trans }}</a>
                        {% endif %}

                        {% if child.donor is null %}
                            <a href="{{ path('app_become_a_donor_campaign', {id: child.id}) }}"
                               class="btn btn-primary">{{ 'give.this.child.a.present'|trans }}</a>
                        {% else %}
                            <p>{{ 'this.child.is.already.gifted'|trans }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if not is_granted('IS_AUTHENTICATED_FULLY') or not app.user == campaign %}
        <div class="row">
            <div class="col">
                <h3>{{ 'login'|trans }}</h3>
                <p>{{ 'we.will.send.an.email.to.the.campaign.owner.with.a.magic.link'|trans }}</p>
                <form action="{{ path('login') }}" method="POST">
                    <input type="hidden" name="campaign" value="{{ campaign.id }}">
                    <button class="btn btn-secondary"
                            type="submit">{{ 'send.magic.login.link.to.campaign.owner'|trans }}</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}